---

packages:
  - nginx
  - php5-cli
  - php5-mysql
  - php5-fpm
  - php-apc
  - php5-mysql
  - php5-curl
  - libmime-lite-perl

firewall_role_rules:
  - "-A INPUT -p tcp -m tcp --dport 80 -j ACCEPT"

sysctls:
  - name: net.ipv4.ip_local_port_range
    value: "'1024 65000'"
  - name: net.ipv4.tcp_tw_reuse
    value: 1
  - name: net.ipv4.tcp_fin_timeout
    value: 15
  - name: net.core.netdev_max_backlog
    value: 4096
  - name: net.core.rmem_max
    value: 16777216
  - name: net.core.somaxconn
    value: 4096
  - name: net.core.wmem_max
    value: 16777216
  - name: net.ipv4.tcp_max_syn_backlog
    value: 20480
  - name: net.ipv4.tcp_max_tw_buckets
    value: 400000
  - name: net.ipv4.tcp_no_metrics_save
    value: 1
  - name: net.ipv4.tcp_rmem
    value: "'4096 87380 16777216'"
  - name: net.ipv4.tcp_syn_retries
    value: 2
  - name: net.ipv4.tcp_synack_retries
    value: 2
  - name: net.ipv4.tcp_wmem
    value: "'4096 65536 16777216'"

# vim: set textwidth=0 ft=yaml ts=2 sw=2 expandtab:
