---
# Playbook permettant de deployer une configuration openssh server basee uniquement sur les algo les plus costauds actuels

- name: Deployer la configuration ssh courbe elliptique
  hosts: all
  user: root
  gather_facts: yes

  roles:
    - ssh-curve

# vim: set textwidth=0 ft=yaml ts=2 sw=2 expandtab:
