---

- name: Update host --- tags - normal, packages, ldconfig, restart
  hosts: all
  user: root
  gather_facts: yes
  serial: 1
  max_fail_percentage: 1
           
  
  roles:
    - role: update
  
