---
## Install and configure rudder-agent on debian/ubuntu node
- name: add rudder repo key -- debian
  apt_key: url="https://www.rudder-project.org/apt-repos/rudder_apt_key.pub" state=present
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: remove older rudder repo url -- debian
  apt_repository:
    repo: 'deb http://repository.rudder.io/apt/{{ item }}/ {{ansible_distribution_release}} main'
    state: absent
    filename: 'rudder'
    update_cache: yes
  with_items:
    - 4.1
    - 5.0
    - 6.0
    - 6.1
    - 6.2
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Add 7.0 rudder repo url
  apt_repository:
    repo: 'deb http://repository.rudder.io/apt/7.0/ {{ansible_distribution_release}} main'
    state: present
    filename: 'rudder-apt'
    update_cache: yes
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: install rudder agent -- debian
  apt: pkg=rudder-agent state=latest update_cache=yes
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  notify:
    - agent-run

- name: configure rudder server -- debian
  template:  src=policy_server.dat.tpl dest=/var/rudder/cfengine-community/policy_server.dat
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  notify:
      - rudder-start
      - agent-inventory
      - agent-run
