---
##
##
## Role to install xymon client or xymon server on host depending what is needed
##
## Tags :
##   - xymon-server : binaries and configuration server side
##   - xymon-client : binaries and configuration client side (need a working server)
##   - client-configuration : used to configure client only (no binaries)
##   - client-packages : used only install client binaries (no configuration)
##   - server-configuration : used to configure server only (no binaries)
##   - server-packages : used to only install server binaries (no configuration)
########

##Check vars
- name: check xymon_server
  fail: msg="Missing variable xymon_server"
  tags:
    - xymon-client
    - xymon-server
  when: xymon_server is not defined

- name: check xymon_checks
  fail: msg="Missing variable xymon_checks"
  tags:
    - xymon-client
    - client-configuration
  when: xymon_checks is not defined

- name: check monitoring_ip
  fail: msg="Missing variable monitoring_ip"
  tags:
    - xymon-client
    - client-configuration
  when: monitoring_ip is not defined

- name: check server htpasswd name
  fail: msg="Missing variable xymon_htname"
  tags:
    - xymon-server
    - server-configuration
  when: xymon_htname is not defined

- name: check server htpasswd password
  fail: msg="Missing variable xymon_htpasswd"
  tags:
    - xymon-server
    - server-configuration
  when: xymon_htpasswd is not defined

##Main tasks
- include: client.yml
